apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx        # must be the same value as the label in the template 
  template:
    metadata:
      labels:
        app: nginx      # this label is assigned to each pod in the set
    spec:
      containers:
      - name: nginx
        image: nginx:alpine