---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-leon
  labels:
    app: nginx
    pod-template-hash: 7fb7fd49b4
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80