apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-09-26T13:18:55Z"
  generation: 1
  labels:
    app: nginx2
  name: nginx2
  namespace: othernamespace
  resourceVersion: "1023601"
  uid: fa48a89b-d45e-46d8-be25-5f1706e84ff9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx2
    spec:
      containers:
      - image: registry.gitlab.com/baggypants/trio-task/nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
