# Mysql
# Service port 3306
# Service type ClusterIP
# Service Name `mysql`
# Deployment config needs to set:
# MYSQL_ROOT_PASSWORD=[PASSWORD]
# MYSQL_DATABASE=flask-db
#
# registry.gitlab.com/baggypants/trio-task/db

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: registry.gitlab.com/baggypants/trio-task/db
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP