# Nginx is doing a proxy pass to 
# flask-app:5000
# Nginx will listen on port 80
# Deployment config
# service Loadbalancer 
# Image
# registry.gitlab.com/baggypants/trio-task/nginx

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    prog: trio2
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        prog: trio2
    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: my-config
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
         - name: nginx-config-volume
           mountPath: /etc/nginx/conf.d
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    prog: trio2
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer