# flask app listening on port 5000
# Service ClusterIP port 5000
# service name must be 'flask-app'
# 
# Image
#registry.gitlab.com/baggypants/trio-task/flask-app
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: registry.gitlab.com/baggypants/trio-task/flask-app:220926
        name: flask-app
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: MYSQL_PASSWORD
          value: password123
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP